# Generated by Django 5.2.7 on 2025-11-06 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='用户名（冗余）')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('action_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('view', '查看'), ('list', '列表'), ('other', '其他')], db_index=True, default='other', max_length=20, verbose_name='操作类型')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='对象ID')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='对象描述')),
                ('request_path', models.CharField(blank=True, default='', max_length=500, verbose_name='请求路径')),
                ('request_method', models.CharField(blank=True, default='', max_length=10, verbose_name='请求方法')),
                ('request_params', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='浏览器信息')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='对象类型')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_opera_user_id_5d9cb4_idx'), models.Index(fields=['action_type', '-created_at'], name='audit_opera_action__caf37b_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_opera_content_437198_idx'), models.Index(fields=['request_path', '-created_at'], name='audit_opera_request_5696a5_idx'), models.Index(fields=['ip_address', '-created_at'], name='audit_opera_ip_addr_9d11e0_idx')],
            },
        ),
    ]
