# Generated by Django 5.2.7 on 2025-11-05 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('job_name', models.CharField(max_length=100, unique=True, verbose_name='任务名称')),
                ('invoke_target', models.CharField(max_length=255, verbose_name='调用目标')),
                ('job_params', models.JSONField(blank=True, default=list, verbose_name='参数')),
                ('cron_expression', models.CharField(default='* * * * *', max_length=100, verbose_name='Cron表达式')),
                ('next_valid_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('status', models.IntegerField(choices=[(0, '停用'), (1, '启用')], default=1, verbose_name='状态')),
                ('job_id', models.CharField(blank=True, default='', editable=False, max_length=128, verbose_name='调度器任务ID')),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='最后执行时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to='rbac.organization', verbose_name='归属组织')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
